/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pontoeletronico;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonn
 */
public class Add extends javax.swing.JFrame {

        Utilidades.ConectaBanco conexao = new Utilidades.ConectaBanco();
       
 String pegalogsen = "select login,senha,funcao from login";
 	String url = "jdbc:oracle:thin:@localhost:1521:xe";
      String inserir = "insert into login values (?,?,?,?,?)" ;
      //String criatabela = "CREATE TABLE "++" (data varchar(20),entrada varchar(20),saidaal varchar(20),entradaal varchar(20),saida varchar(20))";
    public Add() {
        conexao.conexao();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldDataNascimento = new javax.swing.JTextField();
        jCheckBoxFuncionario = new javax.swing.JCheckBox();
        jCheckBox2Gerente = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jButtonok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldnome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldnomeMouseClicked(evt);
            }
        });
        jTextFieldnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeActionPerformed(evt);
            }
        });

        jTextFieldDataNascimento.setText("DD/MM/AAAA");
        jTextFieldDataNascimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDataNascimentoMouseClicked(evt);
            }
        });
        jTextFieldDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataNascimentoActionPerformed(evt);
            }
        });

        jCheckBoxFuncionario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBoxFuncionario.setText("Funcionário");
        jCheckBoxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFuncionarioActionPerformed(evt);
            }
        });

        jCheckBox2Gerente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox2Gerente.setText("Gerente");
        jCheckBox2Gerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2GerenteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("Cadastro de Funcionário");

        jButtonok.setText("OK");
        jButtonok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonokActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Data de Nascimento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBoxFuncionario)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox2Gerente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonok, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox2Gerente)
                        .addContainerGap(39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonok)
                        .addGap(27, 27, 27))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldnomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomeMouseClicked

    private void jTextFieldnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeActionPerformed

    }//GEN-LAST:event_jTextFieldnomeActionPerformed

    private void jTextFieldDataNascimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDataNascimentoMouseClicked
        // TODO add your handling code here:
        
        jTextFieldDataNascimento.setText(null);
        
    }//GEN-LAST:event_jTextFieldDataNascimentoMouseClicked

    private void jTextFieldDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataNascimentoActionPerformed

    private void jCheckBoxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFuncionarioActionPerformed

        if(jCheckBoxFuncionario.isSelected()){

            jCheckBox2Gerente.setEnabled(false);
        }
        else {
            jCheckBox2Gerente.setEnabled(true);
        }

    }//GEN-LAST:event_jCheckBoxFuncionarioActionPerformed

    private void jCheckBox2GerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2GerenteActionPerformed
     if(jCheckBox2Gerente.isSelected()){
    
            jCheckBoxFuncionario.setEnabled(false);
    } 
        else {
                jCheckBoxFuncionario.setEnabled(true);
                
    }//GEN-LAST:event_jCheckBox2GerenteActionPerformed
    }
    
    private void jButtonokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonokActionPerformed
     
        String nome = jTextFieldnome.getText();
      String tabela = nome.replace(' ', '_').toUpperCase();
       String dataNascimento = jTextFieldDataNascimento.getText();
        String senha = "1234";

        String login = nome.substring(0, 4).toLowerCase()+senha;

        try(PreparedStatement pst = conexao.conn.prepareStatement(inserir)){

            pst.setString(1, login);
            pst.setString(2, senha);
            pst.setString(3, nome.toUpperCase());
            if(jCheckBox2Gerente.isSelected()){
                pst.setString(4,"G");
            }else {
                pst.setString(4,"F");
            }
            pst.setString(5, jTextFieldDataNascimento.getText());
            pst.addBatch();
            pst.executeBatch();
        }

        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel criar o cadastro corretamente");
        }
        // System.out.println(senha +"\n  \n"+ login+"");
String criatabela = "CREATE TABLE "+login+" (data varchar(20),entrada varchar(20),saidaal varchar(20),entradaal varchar(20),saida varchar(20),flag varchar(4))";
     
try(PreparedStatement pst2 = conexao.conn.prepareStatement(criatabela)){
         
            pst2.executeUpdate();
      
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null," Erro ao criar funionario ");
     }
      
        
        this.dispose();  
    
    }//GEN-LAST:event_jButtonokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonok;
    private javax.swing.JCheckBox jCheckBox2Gerente;
    private javax.swing.JCheckBox jCheckBoxFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldDataNascimento;
    private javax.swing.JTextField jTextFieldnome;
    // End of variables declaration//GEN-END:variables
}
