/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pontoeletronico;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonn
 */
public class ConfirmaPont extends javax.swing.JFrame {

        Utilidades.ConectaBanco conexao = new Utilidades.ConectaBanco();
   
 	String nome;
    	String url = "jdbc:oracle:thin:@localhost:1521:xe";
     
        String ponto;
         //Date datas = new Date();
        //SimpleDateFormat fd = new SimpleDateFormat("dd/MM/yyyy");
       // String data = fd.format(datas);
        String dataatual;
    
        Date horas = new Date();
        SimpleDateFormat f = new SimpleDateFormat("HH:mm");
        String hora = f.format(horas);
        String tabela,entrada,saidaal,entradaal,saida;
        
        int checkdataatual;
        
    public ConfirmaPont(int checkdataatual,String data,String nome,String entrada,String saidaal,String entradaal,String saida) {
        initComponents();
        conexao.conexao();
        this.nome = nome;
        this.dataatual = data;
      //  this.hora = hora;
        jhoraponto.setText(hora);
        this.tabela = nome;
        this.checkdataatual = checkdataatual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTipoPonto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jhoraponto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel1.setText("Confirma o Ponto de ");

        jTipoPonto.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jTipoPonto.setText("Saida");

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jLabel3.setText("ás ");

        button1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button1.setLabel("Sim");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        button2.setLabel("Não");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jhoraponto.setFont(new java.awt.Font("Microsoft YaHei", 0, 24)); // NOI18N
        jhoraponto.setText("--:--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(jTipoPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jhoraponto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(84, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTipoPonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jhoraponto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        setSize(new java.awt.Dimension(517, 277));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
 
        this.dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
    
     // String  baterponto = "select flag from "+nome+ " where data='"+dataatual+"'" ;   
 
      
      
      
      //verifica a data se é atual e seta a flag para o 1;
      
       String inseriflag = "insert into "+nome+" (flag,data,entrada) values (1,'"+dataatual+"','"+hora+"')";
       
        if (checkdataatual == 1 )  {          
                                     try(PreparedStatement pst2 = conexao.conn.prepareStatement(inseriflag)){
                                          pst2.executeUpdate();

                                } catch (SQLException ex) {
                                    JOptionPane.showMessageDialog(null," Erro ao bater ponto na data diferente  ");
                             }
                                   }  
      
  
       if (checkdataatual == 3){  
           
           baterpontonobanco();
      
                 try(PreparedStatement pst3 = conexao.conn.prepareStatement(ponto)){
                                                              pst3.executeUpdate();
                                
                                                    } catch (SQLException ex) {
                                                        JOptionPane.showMessageDialog(null,"Não foi Possível Bater Ponto !");
                                                 }
       }
       
       this.dispose();

    }//GEN-LAST:event_button1ActionPerformed

    // Metodo de bater ponto nas flags 2,3,4
  
    public void baterpontonobanco(){
    String  baterponto = "select flag from "+nome+ " where data='"+dataatual+"'" ;  
    
    
try(PreparedStatement pst = conexao.conn.prepareStatement(baterponto);
           ResultSet rs2 = pst.executeQuery()){
             
         while(rs2.next()){
 
                         switch (rs2.getString(1)) {
                            
                             case "1":
                                 ponto = "update "+nome+" set saidaal='"+hora+"',flag='2' where data='"+dataatual+"'";
                             break;
                             case "2":
                                   ponto = "update "+nome+" set entradaal='"+hora+"',flag='3' where data='"+dataatual+"'";
                                 break;
                             case "3":
                                 ponto = "update "+nome+" set saida='"+hora+"',flag='4' where data='"+dataatual+"'";
                                 break; 
                           
                         }
         }
               
     }  catch (SQLException ex) {
         Logger.getLogger(Ponto.class.getName()).log(Level.SEVERE, null, ex);
     }


}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmaPont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmaPont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmaPont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmaPont.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           //     new ConfirmaPont().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jTipoPonto;
    private javax.swing.JLabel jhoraponto;
    // End of variables declaration//GEN-END:variables
}
